target:
  url: "localhost:9200"
  index: unified

sources:
  - url: "localhost:9201"
    index: brederode
    fields:
      - source: fromLocation
      - source: toLocation
      - source: recipient
      - source: sender
      - source: title
      - source: datePublished
        lambda: "x: {'date': {'gte': x, 'lte': x}}"
        target: date
      - source: datePublished
        target: dateSortable
      - source: letterText
        target: letterOriginalText
      - lambda: "_: 'letter'"
        target: type

  - url: "localhost:9202"
    index: israels
    fields:
      - source: sender
      - source: persons
      - source: type
      - source: date
      - source: dateSortable
      - source: correspondent
        target: recipient
      - source: location
        target: fromLocation
      - source: titleNL
        target: title
